# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

workspace = special:music, on-created-empty:spotify
workspace = special:activity, on-created-empty:$terminal -e btop
workspace = special:docker, on-created-empty:$terminal -e lazydocker
workspace = special:terminal, on-created-empty:alacritty

# center the pops excepting context menu
#windowrulev2 = move 30% 30%,class:^jetbrains-(?!toolbox),title:^(?!win.*),floating:1
#windowrulev2 = size 40% 40%,class:^jetbrains-(?!toolbox),title:^(?!win.*),floating:1

# Fix tooltips (always have a title of `win.<id>`)
# Fix for sidebar menus being unclickable
#windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^(win.*)$
#windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^(win.*)$
# Fix tab dragging (always have a single space character as their title)
#windowrulev2 = noinitialfocus, class:^(.*jetbrains.*)$, title:^\\s$
#windowrulev2 = nofocus, class:^(.*jetbrains.*)$, title:^\\s$
# Additional fixes for tab dragging
windowrulev2 = tag +jb-window, class:^jetbrains-.+$,floating:1
windowrulev2 = tag +jb-ide, class:^jetbrains-.+$,floating:0
#windowrulev2 = stayfocused, tag:jb
windowrulev2 = focusonactivate on, tag:jb-window
windowrulev2 = allowsinput on, tag:jb-window
windowrulev2 = pin, tag:jb-window
#windowrulev2 = suppressevent fullscreen maximize activate activatefocus fullscreenoutput, tag:jb-window
#windowrulev2 = float, tag:jb-window
#windowrulev2 = maximize,tag:jb
windowrulev2 = noinitialfocus, tag:jb

# This rule sets all windows (class:^(.*)$) to 1.0 opacity when active and inactive.
# The 'override' keyword is often necessary to force the value over existing rules.
#windowrulev2 = opacity 1.0 1.0 override, class:^(.*)$
